## Reading text file

In [3]:
filename = 'mybox_short.txt'
file = open(filename, mode='r') #r is to read; w is to write
text = file.read()
file.close

<function TextIOWrapper.close()>

In [4]:
print(text)

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.90])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
Received: from holes.mr.itd.umich.edu (holes.mr.itd.umich.edu [141.211.14.79])
	by flawless.mail.umich.edu () with ESMTP id m05EEFR1013674;
	Sat, 5 Jan 2008 09:14:15 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY holes.mr.itd.umich.edu ID 477F90B0.2DB2F.12494 ; 
	 5 Jan 2008 09:14:10 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 5F919BC2F2;
	Sat,  5 Jan 2008 14:10:05 +0000 (GMT)
Message-ID: <200801051412.m05ECIaH010327@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit



In [6]:
with open(filename,'r') as file:
    print(file.read())

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
Return-Path: <postmaster@collab.sakaiproject.org>
Received: from murder (mail.umich.edu [141.211.14.90])
	 by frankenstein.mail.umich.edu (Cyrus v2.3.8) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
X-Sieve: CMU Sieve 2.3
Received: from murder ([unix socket])
	 by mail.umich.edu (Cyrus v2.2.12) with LMTPA;
	 Sat, 05 Jan 2008 09:14:16 -0500
Received: from holes.mr.itd.umich.edu (holes.mr.itd.umich.edu [141.211.14.79])
	by flawless.mail.umich.edu () with ESMTP id m05EEFR1013674;
	Sat, 5 Jan 2008 09:14:15 -0500
Received: FROM paploo.uhi.ac.uk (app1.prod.collab.uhi.ac.uk [194.35.219.184])
	BY holes.mr.itd.umich.edu ID 477F90B0.2DB2F.12494 ; 
	 5 Jan 2008 09:14:10 -0500
Received: from paploo.uhi.ac.uk (localhost [127.0.0.1])
	by paploo.uhi.ac.uk (Postfix) with ESMTP id 5F919BC2F2;
	Sat,  5 Jan 2008 14:10:05 +0000 (GMT)
Message-ID: <200801051412.m05ECIaH010327@nakamura.uits.iupui.edu>
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit



## Importing flat files using numpy

In [7]:
import numpy as np

In [10]:
filename = 'TPASTE.txt'
data = np.loadtxt(filename)
data

array([[0.108, 0.424, 2.07 , 2.05 ],
       [0.166, 0.482, 2.17 , 2.1  ],
       [0.126, 0.428, 2.17 , 2.04 ],
       ...,
       [0.391, 0.19 , 1.71 , 1.8  ],
       [0.473, 0.249, 1.76 , 1.81 ],
       [0.384, 0.172, 1.81 , 1.67 ]])

In [12]:
data1 = np.genfromtxt(filename)
data1

array([[0.108, 0.424, 2.07 , 2.05 ],
       [0.166, 0.482, 2.17 , 2.1  ],
       [0.126, 0.428, 2.17 , 2.04 ],
       ...,
       [0.391, 0.19 , 1.71 , 1.8  ],
       [0.473, 0.249, 1.76 , 1.81 ],
       [0.384, 0.172, 1.81 , 1.67 ]])

In [13]:
data2 = np.loadtxt(filename,skiprows=1)
data2

array([[0.166, 0.482, 2.17 , 2.1  ],
       [0.126, 0.428, 2.17 , 2.04 ],
       [0.115, 0.397, 2.07 , 1.96 ],
       ...,
       [0.391, 0.19 , 1.71 , 1.8  ],
       [0.473, 0.249, 1.76 , 1.81 ],
       [0.384, 0.172, 1.81 , 1.67 ]])

In [21]:
data3 = np.loadtxt(filename,skiprows=1,usecols=[0,2,3],max_rows=10)
data3

array([[0.166, 2.17 , 2.1  ],
       [0.126, 2.17 , 2.04 ],
       [0.115, 2.07 , 1.96 ],
       [0.119, 2.12 , 2.06 ],
       [0.176, 2.05 , 2.01 ],
       [0.155, 2.1  , 2.03 ],
       [0.118, 2.07 , 2.09 ],
       [0.136, 2.1  , 2.01 ],
       [0.137, 2.14 , 2.04 ],
       [0.124, 2.12 , 2.03 ]])

In [22]:
data4 = np.loadtxt(filename,skiprows=1,usecols=[0,2,3],max_rows=10,dtype='str')
data4

array([['0.166', '2.17', '2.1'],
       ['0.126', '2.17', '2.04'],
       ['0.115', '2.07', '1.96'],
       ['0.119', '2.12', '2.06'],
       ['0.176', '2.05', '2.01'],
       ['0.155', '2.1', '2.03'],
       ['0.118', '2.07', '2.09'],
       ['0.136', '2.1', '2.01'],
       ['0.137', '2.14', '2.04'],
       ['0.124', '2.12', '2.03']], dtype='<U5')

# Other types

## Pickled files: are serialized, which means it can be converted to bytestream

In [23]:
import pickle

In [25]:
dogs_dict = { 'Ozzy': 3, 'Filou': 8, 'Luna': 5, 'Skippy': 10, 'Barco': 12, 
             'Balou': 9, 'Laika': 16 }
filename = 'dog'
outfile = open(filename,'wb')
pickle.dump(dogs_dict,outfile)
outfile.close()

In [27]:
with open('dog','rb') as file:
    data = pickle.load(file)
print(data)

{'Ozzy': 3, 'Filou': 8, 'Luna': 5, 'Skippy': 10, 'Barco': 12, 'Balou': 9, 'Laika': 16}


## Excel

In [28]:
import pandas as pd

In [30]:
file = 'battledeath.xlsx'
data = pd.ExcelFile(file)
print(data.sheet_names)

['2002', '2004']


In [32]:
df1 = data.parse('2002')
df1.head()

War, age-adjusted mortality due to       2002
0                        Afghanistan  36.083990
1                            Albania   0.128908
2                            Algeria  18.314120
3                            Andorra   0.000000
4                             Angola  18.964560

In [33]:
df2 = data.parse(0)
df2.head()

War, age-adjusted mortality due to       2002
0                        Afghanistan  36.083990
1                            Albania   0.128908
2                            Algeria  18.314120
3                            Andorra   0.000000
4                             Angola  18.964560

## SAS and Stata files

SAS:Statistical Analysis System, focus on business analytics and biostatistic  
Stata:"Statistics"+"data", focus on academic social sciences research

In [35]:
from sas7bdat import SAS7BDAT 

In [36]:
with SAS7BDAT('sales.sas7bdat') as file:
    df_sas = file.to_data_frame()
df_sas.head()

YEAR     P           S
0  1950.0  12.9  181.899994
1  1951.0  11.9  245.000000
2  1952.0  10.7  250.199997
3  1953.0  11.3  265.899994
4  1954.0  11.2  248.500000

In [37]:
data_sta = pd.read_stata('disarea.dta')
data_sta.head()

wbcode               country  disa1  disa2  disa3  disa4  disa5  disa6  \
0    AFG           Afghanistan   0.00   0.00   0.76   0.73    0.0   0.00   
1    AGO                Angola   0.32   0.02   0.56   0.00    0.0   0.00   
2    ALB               Albania   0.00   0.00   0.02   0.00    0.0   0.00   
3    ARE  United Arab Emirates   0.00   0.00   0.00   0.00    0.0   0.00   
4    ARG             Argentina   0.00   0.24   0.24   0.00    0.0   0.23   

   disa7  disa8  ...  disa16  disa17  disa18  disa19  disa20  disa21  disa22  \
0   0.00    0.0  ...     0.0     0.0     0.0    0.00    0.00     0.0    0.00   
1   0.56    0.0  ...     0.0     0.4     0.0    0.61    0.00     0.0    0.99   
2   0.00    0.0  ...     0.0     0.0     0.0    0.00    0.00     0.0    0.00   
3   0.00    0.0  ...     0.0     0.0     0.0    0.00    0.00     0.0    0.00   
4   0.00    0.0  ...     0.0     0.0     0.0    0.00    0.05     0.0    0.00   

   disa23  disa24  disa25  
0    0.02    0.00    0.00  
1    0.98    0.61    0.00  
2    0.00    0.00    0.16  
3    0.00    0.00    0.00  
4    0.01    0.00    0.11  

[5 rows x 27 columns]

## HDF5

Hierarchical Data Format version 5: Standard for storing large quantities of numerical data

In [38]:
import h5py
filename = 'L-L1_LOSC_4_V1-1126259446-32.hdf5'
data = h5py.File(filename,'r')
print(type(data))

<class 'h5py._hl.files.File'>


In [39]:
for key in data.keys():
    print(key)

meta
quality
strain


In [40]:
print(type(data['meta']))

<class 'h5py._hl.group.Group'>


In [41]:
for key in data['meta'].keys():
    print(key)

Description
DescriptionURL
Detector
Duration
GPSstart
Observatory
Type
UTCstart


In [46]:
print(data['meta']['Description'].value)

b'Strain data time series from LIGO'


## Matlab

In [47]:
import scipy.io

In [48]:
filename = 'ja_data2.mat'
mat = scipy.io.loadmat(filename)
print(type(mat))

<class 'dict'>


## os : explore working directory

In [52]:
import os
wd = os.getcwd()
os.listdir(wd)

['disarea.dta',
 'dog',
 'TPASTE.TXT',
 'sales.sas7bdat',
 'ja_data2.mat',
 'battledeath.xlsx',
 'titanic_sub.csv',
 'Chinook.sqlite',
 'L-L1_LOSC_4_V1-1126259446-32.hdf5',
 'mnist_kaggle_some_rows.csv',
 'Introduction to importing data.ipynb',
 '.ipynb_checkpoints',
 'seaslug.txt',
 'mybox_short.txt']

# Rational database

Management systems: PostgreSQL, MySQL, SQLite

In [54]:
from sqlalchemy import create_engine

In [65]:
engine = create_engine('sqlite:///Chinook.sqlite') 
#depends on the document name in the same working directory, if name is aaa.sqlite, 
#create_engine('sqlite:///aaa.sqlite')

In [66]:
table_names = engine.table_names()
print(table_names)

['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']


In [79]:
con = engine.connect()

In [80]:
rs = con.execute("SELECT * FROM Customer")

In [81]:
df = pd.DataFrame(rs.fetchall())
df.columns = rs.keys()
con.close()

In [82]:
df.head()

CustomerId  FirstName     LastName  \
0           1       Luís    Gonçalves   
1           2     Leonie       Köhler   
2           3   François     Tremblay   
3           4      Bjørn       Hansen   
4           5  František  Wichterlová   

                                            Company  \
0  Embraer - Empresa Brasileira de Aeronáutica S.A.   
1                                              None   
2                                              None   
3                                              None   
4                                  JetBrains s.r.o.   

                           Address                 City State         Country  \
0  Av. Brigadeiro Faria Lima, 2170  São José dos Campos    SP          Brazil   
1          Theodor-Heuss-Straße 34            Stuttgart  None         Germany   
2                1498 rue Bélanger             Montréal    QC          Canada   
3                 Ullevålsveien 14                 Oslo  None          Norway   
4                    Klanova 9/506               Prague  None  Czech Republic   

  PostalCode               Phone                 Fax  \
0  12227-000  +55 (12) 3923-5555  +55 (12) 3923-5566   
1      70174    +49 0711 2842222                None   
2    H2G 1A7   +1 (514) 721-4711                None   
3       0171     +47 22 44 22 22                None   
4      14700    +420 2 4172 5555    +420 2 4172 5555   

                      Email  SupportRepId  
0      luisg@embraer.com.br             3  
1     leonekohler@surfeu.de             5  
2       ftremblay@gmail.com             3  
3     bjorn.hansen@yahoo.no             4  
4  frantisekw@jetbrains.com             4

In [85]:
with engine.connect() as con:
    rs = con.execute('SELECT CustomerId, FirstName, City FROM Customer')
    df = pd.DataFrame(rs.fetchmany(size=5))
    df.columns = rs.keys()
print(df)

   CustomerId  FirstName                 City
0           1       Luís  São José dos Campos
1           2     Leonie            Stuttgart
2           3   François             Montréal
3           4      Bjørn                 Oslo
4           5  František               Prague


In [86]:
df = pd.read_sql_query('SELECT * FROM Customer',engine)
df.head()

CustomerId  FirstName     LastName  \
0           1       Luís    Gonçalves   
1           2     Leonie       Köhler   
2           3   François     Tremblay   
3           4      Bjørn       Hansen   
4           5  František  Wichterlová   

                                            Company  \
0  Embraer - Empresa Brasileira de Aeronáutica S.A.   
1                                              None   
2                                              None   
3                                              None   
4                                  JetBrains s.r.o.   

                           Address                 City State         Country  \
0  Av. Brigadeiro Faria Lima, 2170  São José dos Campos    SP          Brazil   
1          Theodor-Heuss-Straße 34            Stuttgart  None         Germany   
2                1498 rue Bélanger             Montréal    QC          Canada   
3                 Ullevålsveien 14                 Oslo  None          Norway   
4                    Klanova 9/506               Prague  None  Czech Republic   

  PostalCode               Phone                 Fax  \
0  12227-000  +55 (12) 3923-5555  +55 (12) 3923-5566   
1      70174    +49 0711 2842222                None   
2    H2G 1A7   +1 (514) 721-4711                None   
3       0171     +47 22 44 22 22                None   
4      14700    +420 2 4172 5555    +420 2 4172 5555   

                      Email  SupportRepId  
0      luisg@embraer.com.br             3  
1     leonekohler@surfeu.de             5  
2       ftremblay@gmail.com             3  
3     bjorn.hansen@yahoo.no             4  
4  frantisekw@jetbrains.com             4

In [89]:
df = pd.read_sql_query('SELECT * FROM Customer INNER JOIN Invoice on Customer.CustomerId=Invoice.CustomerId',engine)
df.head()

CustomerId FirstName LastName Company                  Address       City  \
0           2    Leonie   Köhler    None  Theodor-Heuss-Straße 34  Stuttgart   
1           4     Bjørn   Hansen    None         Ullevålsveien 14       Oslo   
2           8      Daan  Peeters    None          Grétrystraat 63   Brussels   
3          14      Mark  Philips   Telus           8210 111 ST NW   Edmonton   
4          23      John   Gordon    None          69 Salem Street     Boston   

  State  Country PostalCode              Phone  ... SupportRepId InvoiceId  \
0  None  Germany      70174   +49 0711 2842222  ...            5         1   
1  None   Norway       0171    +47 22 44 22 22  ...            4         2   
2  None  Belgium       1000   +32 02 219 03 03  ...            4         3   
3    AB   Canada    T6G 2C7  +1 (780) 434-4554  ...            5         4   
4    MA      USA       2113  +1 (617) 522-1333  ...            4         5   

   CustomerId          InvoiceDate           BillingAddress BillingCity  \
0           2  2007-01-01 00:00:00  Theodor-Heuss-Straße 34   Stuttgart   
1           4  2007-01-02 00:00:00         Ullevålsveien 14        Oslo   
2           8  2007-01-03 00:00:00          Grétrystraat 63    Brussels   
3          14  2007-01-06 00:00:00           8210 111 ST NW    Edmonton   
4          23  2007-01-11 00:00:00          69 Salem Street      Boston   

  BillingState BillingCountry BillingPostalCode  Total  
0         None        Germany             70174   1.98  
1         None         Norway              0171   3.96  
2         None        Belgium              1000   5.94  
3           AB         Canada           T6G 2C7   8.91  
4           MA            USA              2113  13.86  

[5 rows x 22 columns]